version: "3"
services:
  cb4:
    restart: always
    image: jioj/cb4
    container_name: cb4
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - 34765:34765
    privileged: true
    networks:
      - default
    environment:
      DB_HOST: mongo
      MQ_HOST: rabbitmq
  mongo:
    restart: always
    image: mvertes/alpine-mongo
    container_name: mongo
    volumes:
      - ~/mongo_data:/data/db
    networks:
      - default
  rabbitmq:
    restart: always
    image: rabbitmq:alpine
    container_name: rabbitmq
    networks:
      - default
networks:
  default:
